org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.77
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=ladisdirewolves
mod_name=Ladis' Direwolves
mod_license=MIT
mod_version=1.1.1
mod_group_id=com.ladis.direwolves
mod_authors=Ladis
mod_description=Adds Direwolves - evolved wolves with custom model and animations.
