modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "Ladis_Direwolves.png"
description = """Ladis' Direwolves is a mod that transforms ordinary wolves into loyal, powerful, and upgradable companions. Forget about pets that quickly perish in battle — now your wolf will become a true combat partner and a reliable mount!"""

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "geckolib"
    type = "required"
    versionRange = "[4.7,)"
    ordering = "AFTER"
    side = "BOTH"
